import Config

# Configure your database
config :hospitality_coms, HospitalityComs.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "hospitality_coms_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# A different Postgres role from the one above (#17). See `config/test.exs` for
# why the password is a literal here; roles are cluster-global, so the
# `employer_login` created by the test database's migration is the same role
# this connects as.
config :hospitality_coms, HospitalityComs.EmployerRepo,
  username: "employer_login",
  password: "employer_login",
  hostname: "localhost",
  database: "hospitality_coms_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# The demo needs to walk an engagement through its lifecycle without waiting
# for wall-clock time. This implementation does not exist in the production
# build.
config :hospitality_coms, clock: HospitalityComs.Clock.Offset

# No queue runs and no plugin ticks here either, and in `:dev` the reason is
# sharper than the one `config/test.exs` gives.
#
# **Oban's cron stages at real wall-clock time; its workers read the injected
# clock.** `Oban.Plugins.Cron` inserts `RetentionSweeper` hourly at the real
# instant and it stages immediately, and `RetentionSweeper.perform/1` is
# `Lifecycle.sweep(Clock.now())` — the *offset* clock. So with queues running,
# `POST /api/demo/clock {"advance": {"day": 31}}` and nothing else deletes a
# month of retained messages within the hour, unattended, and
# `EngagementSweeper` stamps archive deadlines within five minutes. The
# wall-clock argument in `HospitalityComs.Demo`'s moduledoc covers the
# *claim-scheduled* `ExpireEngagement` job, which genuinely waits; it does not
# cover cron, which does not.
#
# `Clock.Offset` is `:persistent_term` and node-global, so it survives a code
# reload and a second browser session runs at whatever instant the first left.
# That makes "advancing the clock is the safe control and `run_due_work/0` is
# the dangerous one" false in the one environment the controls exist for.
#
# `HospitalityComs.Demo.run_due_work/0` is therefore the only thing that runs a
# worker in `:dev`, which is also what makes the documented model true where the
# controls actually run. `HospitalityComs.DemoTest` reads this file to assert
# it.
config :hospitality_coms, Oban, testing: :manual

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :hospitality_coms, HospitalityComsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "gNNeaIH8MVweIXXeyeY4F6MgiWBCP8t9LTiekWZ1ElY+a2lSU+f0CGpE6He2KD7w"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable the dev-only mailbox preview route, which is how a magic link is read
# during development now that no page renders one.
config :hospitality_coms, dev_routes: true

# U11's demo controls. `HospitalityComsWeb.DemoController` compiles from
# `dev_support/`, so this key can only ever be true where the module exists;
# setting it in a production config would gate a scope on a module that is not
# there. See `HospitalityComs.Demo`.
config :hospitality_coms, demo_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
