defmodule HospitalityComs.Venues.Venue do
  @moduledoc """
  A venue: the root of the employer zone and the unit an employer session is
  scoped to.

  Every other employer-zone row carries `venue_id`; a venue's own `id` is that
  key, which is why this is the one employer-zone table with no composite
  unique index of its own. There is no `employers` table above it — an employer
  session is scoped to a venue, and `app.employer_id` holds a venue id.

  ## The timezone is required, and it is required for a reason

  Engagement end is end-of-day in the venue's timezone (KTD20). Close shifts
  cross midnight routinely, so a venue whose zone is unknown has no defined
  expiry instant and mid-shift expiry becomes the normal case rather than the
  exotic one. The column is `NOT NULL` and non-empty by check constraint, and
  the value is validated against `pg_timezone_names` — Postgres's own copy of
  the IANA database.

  That validation is a query, so it arrives as a function rather than as a
  list: `changeset/4` takes a `known_timezone?` predicate. It is a required
  argument rather than an option with a permissive default, because a default
  of "assume it is fine" is the shape of a check nobody notices is off.

  Elixir cannot answer the question on its own. The default time zone database
  is `Calendar.UTCOnlyTimeZoneDatabase`, which knows one zone; adding a real
  one is a dependency this POC does not otherwise need, and Postgres is already
  in the transaction.

  ### What that check does not exclude

  `pg_timezone_names` is not a list of IANA zones. It also carries the legacy
  aliases the tz database ships — `GB-Eire`, `EST5EDT`, `Navajo`, and
  `Factory`, which is a placeholder whose local time is deliberately undefined.
  A venue can therefore be created with a name Postgres knows and a wall clock
  nobody should reason about, and end-of-day for it is whatever `AT TIME ZONE`
  happens to return.

  Recorded rather than fixed. Narrowing the list is not obviously right: the
  aliases include names people really type (`US/Pacific`), and a
  hand-maintained allow-list drifts from the database's own copy of IANA, which
  is the drift this validation exists to avoid. The check is worth having as a
  typo catcher; it is not a statement that the zone is one anybody should run a
  venue in. U6 is where end-of-day starts to matter.

  ## No person, no employer key

  There is no `created_by`, no `owner_id`, and no other column naming a human.
  A venue is created by a person, and the record of *which* person belongs on
  the bridge (`engagements`), which U5 builds — see
  `HospitalityComs.Venues` for the argument.

  Timestamps are stamped from the unit of work's instant rather than
  autogenerated, for the reason `HospitalityComs.Accounts.Person` gives: Ecto's
  autogenerate reads the wall clock from inside Ecto, where neither the clock
  nor the check that guards it can reach.
  """

  use Ecto.Schema

  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "venues" do
    field :name, :string
    field :timezone, :string

    timestamps(type: :utc_datetime)
  end

  @type t() :: %__MODULE__{
          __meta__: Ecto.Schema.Metadata.t(),
          id: Ecto.UUID.t() | nil,
          name: String.t() | nil,
          timezone: String.t() | nil,
          inserted_at: DateTime.t() | nil,
          updated_at: DateTime.t() | nil
        }

  @typedoc "Answers whether a string names a zone the database knows."
  @type known_timezone?() :: (String.t() -> boolean())

  @max_name_length 160

  @doc """
  A changeset for a venue, stamped from `now`.

  `id` is **not** castable. Venue creation mints the id before the row exists,
  because the employer scope the insert runs under has to name the venue it is
  about to create — so the id arrives on the struct
  (`Venue.changeset(%Venue{id: minted}, ...)`), which Ecto surfaces into the
  insert, and never out of `attrs`. A primary key taken from user attributes is
  a caller choosing which row to be: it would collide with an existing venue
  and raise `Ecto.ConstraintError` out of a function whose contract is a tuple,
  and it would disagree with the venue the scope and the seeded grant name.

  `known_timezone?` decides whether the timezone names a zone the database
  knows. It is only consulted when a timezone is present and otherwise valid,
  so a missing one is a `can't be blank` rather than a query.
  """
  @spec changeset(t(), map(), DateTime.t(), known_timezone?()) :: Ecto.Changeset.t(t())
  def changeset(venue, attrs, %DateTime{} = now, known_timezone?)
      when is_function(known_timezone?, 1) do
    venue
    |> cast(attrs, [:name, :timezone])
    |> validate_required([:name, :timezone])
    |> update_change(:name, &String.trim/1)
    |> update_change(:timezone, &String.trim/1)
    |> validate_required([:name, :timezone])
    |> validate_length(:name, max: @max_name_length)
    |> validate_timezone(known_timezone?)
    |> check_constraint(:name, name: :venues_name_present, message: "can't be blank")
    |> check_constraint(:name,
      name: :venues_name_within_bound,
      message: "should be at most #{@max_name_length} character(s)"
    )
    |> check_constraint(:timezone, name: :venues_timezone_present, message: "can't be blank")
    |> stamp(now)
  end

  # `validate_change/3` does not run on a field that is already in error or
  # absent, so a blank timezone never reaches the database.
  @spec validate_timezone(Ecto.Changeset.t(t()), known_timezone?()) :: Ecto.Changeset.t(t())
  defp validate_timezone(changeset, known_timezone?) do
    validate_change(changeset, :timezone, fn :timezone, timezone ->
      timezone |> known_timezone?.() |> timezone_errors()
    end)
  end

  @spec timezone_errors(boolean()) :: [{atom(), String.t()}]
  defp timezone_errors(true), do: []
  defp timezone_errors(false), do: [timezone: "is not an IANA time zone name"]

  # A row that has never been inserted gets both stamps; one that has keeps the
  # `inserted_at` it was born with.
  @spec stamp(Ecto.Changeset.t(t()), DateTime.t()) :: Ecto.Changeset.t(t())
  defp stamp(%Ecto.Changeset{data: %__MODULE__{inserted_at: nil}} = changeset, now) do
    stamped_at = DateTime.truncate(now, :second)

    changeset
    |> put_change(:inserted_at, stamped_at)
    |> put_change(:updated_at, stamped_at)
  end

  defp stamp(changeset, now) do
    put_change(changeset, :updated_at, DateTime.truncate(now, :second))
  end
end
